# Generated by Django 3.1.7 on 2021-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='persons',
            field=models.ManyToManyField(default=None, to='person.Person'),
        ),
    ]
