# Generated by Django 3.1.7 on 2021-04-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('todo', '0002_todo_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='persons',
            field=models.ManyToManyField(default=None, to='person.Person'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='github_repo',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
