# Generated by Django 3.1.7 on 2021-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('todo', '0004_auto_20210523_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='persons',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='person.Person'),
        ),
    ]
