# Generated by Django 3.1.7 on 2021-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='resi_number',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
