# Generated by Django 3.1.7 on 2021-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210307_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='resi_number',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
