# Generated by Django 3.1.7 on 2021-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20210307_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_communicate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_meet',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
